export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILURE = "GET_USER_INFO_FAILURE";
export const GET_USER_INFO_PATH = "GetAllUserInfo";

export const TRANSACTION_HISTORY = "TRANSACTION_HISTORY";
export const TRANSACTION_HISTORY_SUCCESS = "TRANSACTION_HISTORY_SUCCESS";
export const TRANSACTION_HISTORY_FAILURE = "TRANSACTION_HISTORY_FAILURE";
export const TRANSACTION_HISTORY_PATH = "GetTransactionHistory";