export const CREATE_BOOKING_RECEIPT = "CREATE_BOOKING_RECEIPT"
export const CREATE_BOOKING_RECEIPT_SUCCESS = "CREATE_BOOKING_RECEIPT_SUCCESS"
export const CREATE_BOOKING_RECEIPT_FAILURE = "CREATE_BOOKING_RECEIPT_FAILURE"
export const CREATE_BOOKING_RECEIPT_PATH = "createBookingReceipt"

export const GET_BOOKING_RECEIPT = "GET_BOOKING_RECEIPT"
export const GET_BOOKING_RECEIPT_SUCCESS = "GET_BOOKING_RECEIPT_SUCCESS"
export const GET_BOOKING_RECEIPT_FAILURE = "GET_BOOKING_RECEIPT_FAILURE"
export const GET_BOOKING_RECEIPT_PATH = "GetBookingReceipt"