export const GET_ALL_AGENT = "GET_ALL_AGENT";
export const GET_ALL_AGENT_SUCCESS = "GET_ALL_AGENT_SUCESS";
export const GET_ALL_AGENT_FAILURE = "GET_ALL_AGENT_FALURE";
export const GET_ALL_AGENT_PATH = "ShowAllAgent";
