export const GET_ALL_SOURCES = "GET_ALL_SOURCES";
export const GET_ALL_SOURCES_SUCCESS = "GET_ALL_SOURCES_SUCESS";
export const GET_ALL_SOURCES_FAILURE = "GET_ALL_SOURCES_FALURE";
export const GET_ALL_SOURCES_PATH = "Showcampaign";
