export const GET_PLOT_TRANSFER_REQ= "GET_PLOT_TRANSFER_REQ";
export const GET_PLOT_TRANSFER_REQ_SUCCESS = "GET_PLOT_TRANSFER_REQ_SUCCESS";
export const GET_PLOT_TRANSFER_REQ_FAILURE = "GET_PLOT_TRANSFER_REQ_FAILURE";
export const GET_PLOT_TRANSFER_REQ_PATH = "getPlotTransferRequests";

