export const FETCH_AGENT_DETAILS = "FETCH_AGENT_DETAILS"
export const FETCH_AGENT_DETAILS_SUCCESS = "FETCH_AGENT_DETAILS_SUCCESS"
export const FETCH_AGENT_DETAILS_FAILURE = "FETCH_AGENT_DETAILS_FAILURE"
export const FETCH_AGENT_DETAILS_PATH = "getRealStateAgentDetails"

export const FETCH_ALL_VERIFIED_CUSTOMER = "FETCH_ALL_VERIFIED_CUSTOMER"
export const FETCH_ALL_VERIFIED_CUSTOMER_SUCCESS = "FETCH_ALL_VERIFIED_CUSTOMER_SUCCESS"
export const FETCH_ALL_VERIFIED_CUSTOMER_FAILURE = "FETCH_ALL_VERIFIED_CUSTOMER_FAILURE"
export const FETCH_ALL_VERIFIED_CUSTOMER_PATH = "getRealStateAgentDetails"

export const UPGRADE_CUSTOMER = "UPGRADE_CUSTOMER"
export const UPGRADE_CUSTOMER_SUCCESS = "UPGRADE_CUSTOMER_SUCCESS"
export const UPGRADE_CUSTOMER_FAILURE = "UPGRADE_CUSTOMER_FAILURE"
export const UPGRADE_CUSTOMER_PATH = "UpgradeCustomer"