export const AMOUNT= "AMOUNT";
export const AMOUNT_SUCCESS = "AMOUNT_SUCCESS";
export const AMOUNT_FAILURE = "AMOUNT_FAILURE";
export const AMOUNT_PATH = "GetCurrencyType";

export const PAYMENTTHROUGH= "PAYMENTTHROUGH";
export const PAYMENTTHROUGH_SUCCESS = "PAYMENTTHROUGH_SUCCESS";
export const PAYMENTTHROUGH_FAILURE = "PAYMENTTHROUGH_FAILURE";
export const PAYMENTTHROUGH_PATH = "GetPaymentThrough";

export const PAYMENTTYPE= "PAYMENTTYPE";
export const PAYMENTTYPE_SUCCESS = "PAYMENTTYPE_SUCCESS";
export const PAYMENTTYPE_FAILURE = "PAYMENTTYPE_FAILURE";
export const PAYMENTTYPE_PATH = "GetPaymentType";

export const PAYMENT_RECIPT= "PAYMENT_RECIPT";
export const PAYMENT_RECIPT_SUCCESS = "PAYMENT_RECIPT_SUCCESS";
export const PAYMENT_RECIPT_FAILURE = "PAYMENT_RECIPT_FAILURE";
export const PAYMENT_RECIPT_PATH = "InserPaymentReceipt";


export const GETTRANSFERINFO= "GETTRANSFERINFO";
export const GETTRANSFERINFO_SUCCESS = "GETTRANSFERINFO_SUCCESS";
export const GETTRANSFERINFO_FAILURE = "GETTRANSFERINFO_FAILURE";
export const GETTRANSFERINFO_PATH = "getTransfreeInfo";


// export const UPDATE_PAYMENT_STAGE= "UPDATE_PAYMENT_STAGE";
// export const UPDATE_PAYMENT_STAGE_SUCCESS = "UPDATE_PAYMENT_STAGE_SUCCESS";
// export const UPDATE_PAYMENT_STAGE_FAILURE = "UPDATE_PAYMENT_STAGE_FAILURE";
// export const UPDATE_PAYMENT_STAGE_PATH = "UpdatePaymentStageStatus";
