export const AGENT = "AGENT";
export const AGENT_SUCCESS = "AGENT_SUCCESS";
export const AGENT_FAILURE = "AGENT_FAILURE";
export const AGENT_PATH = "ShowAllAgent";

export const LEADS = "LEADS";
export const LEADS_SUCCESS = "LEADS_SUCCESS";
export const LEADS_FAILURE = "LEADS_FAILURE";
export const LEADS_PATH = "showallleadsV2";

export const DELETELEADS = "DELETELEADS";
export const DELETELEADS_SUCCESS = "DELETELEADS_SUCCESS";
export const DELETELEADS_FAILURE = "DELETELEADS_FAILURE";
export const DELETELEADS_PATH = "Updateuserstatus";

export const CLIENT = "CLIENT";
export const CLIENT_SUCCESS = "CLIENT_SUCCESS";
export const CLIENT_FAILURE = "CLIENT_FAILURE";
export const CLIENT_PATH = "userplotinfo";

export const CALL_RECORD_DATA = "CALL_RECORD_DATA";
export const CALL_RECORD_DATA_SUCCESS = "CALL_RECORD_DATA_SUCCESS";
export const CALL_RECORD_DATA_FAILURE = "CALL_RECORD_DATA_FAILURE";
export const CALL_RECORD_DATA_PATH = "GetcallrecordsData";

export const INSERTNEWFILE = "INSERTNEWFILE";
export const INSERTNEWFILE_SUCCESS = "INSERTNEWFILE_SUCCESS";
export const INSERTNEWFILE_FAILURE = "INSERTNEWFILE_FAILURE";
export const INSERTNEWFILE_PATH = "insertnewlead";

export const PROJECT = "PROJECT";
export const PROJECT_SUCCESS = "PROJECT_SUCCESS";
export const PROJECT_FAILURE = "PROJECT_FAILURE";
export const PROJECT_PATH = "Projects";

export const PLOTSECTOR = "PLOTSECTOR";
export const PLOTSECTOR_SUCCESS = "PLOTSECTOR_SUCCESS";
export const PLOTSECTOR_FAILURE = "PLOTSECTOR_FAILURE";
export const PLOTSECTOR_PATH = "Sectors";

export const PLOTNO = "PLOTNO";
export const PLOTNO_SUCCESS = "PLOTNO_SUCCESS";
export const PLOTNO_FAILURE = "PLOTNO_FAILURE";
export const PLOTNO_PATH = "Plots";

export const PLOT_POSITION = "PLOT_POSITION";
export const PLOT_POSITION_SUCCESS = "PLOT_POSITION_SUCCESS";
export const PLOT_POSITION_FAILURE = "PLOT_POSITION_FAILURE";
export const PLOT_POSITION_PATH = "PlotPositions";

export const CHANGE_PLOT_POSITION = "CHANGE_PLOT_POSITION";
export const CHANGE_PLOT_POSITION_SUCCESS = "CHANGE_PLOT_POSITION_SUCCESS";
export const CHANGE_PLOT_POSITION_FAILURE = "CHANGE_PLOT_POSITION_FAILURE";
export const CHANGE_PLOT_POSITION_PATH = "changeStatusRequestInitiated";

export const NEW = "NEW";
export const NEW_SUCCESS = "NEW_SUCCESS";
export const NEW_FAILURE = "NEW_FAILURE";
export const NEW_PATH = "PlotPositions";
export const RETURNPLOT = "RETURNPLOT";
export const RETURNPLOT_SUCCESS = "RETURNPLOT_SUCCESS";
export const RETURNPLOT_FAILURE = "RETURNPLOT_FAILURE";
export const RETURNPLOT_PATH = "GetPlotReturnDetail";

export const INSERTRETURNPLOTREQUEST = "INSERTRETURNPLOTREQUEST";
export const INSERTRETURNPLOTREQUEST_SUCCESS =
  "INSERTRETURNPLOTREQUEST_SUCCESS";
export const INSERTRETURNPLOTREQUEST_FAILURE =
  "INSERTRETURNPLOTREQUEST_FAILURE";
export const INSERTRETURNPLOTREQUEST_PATH = "RequestPlotReturn";

export const RETURNPLOT_PATH_V2 = "RETURNPLOT_PATH_V2";
export const RETURNPLOT_PATH_V2_SUCESS = "RETURNPLOT_PATH_V2_SUCESS";
export const RETURNPLOT_PATH_V2_FAILURE = "RETURNPLOT_PATH_V2_FAILURE";
export const RETURNPLOT_PATH_V2_PATH = "GetPlotReturnDetail";
