export const ADD_NEW_SUPPORT = "ADD_NEW_SUPPORT";
export const ADD_NEW_SUPPORT_SUCCESS = "ADD_NEW_SUPPORT_SUCESS";
export const ADD_NEW_SUPPORT_FAILURE = "ADD_NEW_SUPPORT_FALURE";
export const ADD_NEW_SUPPORT_PATH = "insertSupport";

export const FETCH_SUPPORT_TYPE = "FETCH_SUPPORT_TYPE";
export const FETCH_SUPPORT_TYPE_SUCCESS = "FETCH_SUPPORT_TYPE_SUCCESS";
export const FETCH_SUPPORT_TYPE_FAILURE = "FETCH_SUPPORT_TYPE_FAILURE";
export const FETCH_SUPPORT_TYPE_PATH = "getSupportType";

export const FETCH_SUPPORT_BY_TOKEN = "FETCH_SUPPORT_BY_TOKEN";
export const FETCH_SUPPORT_BY_TOKEN_SUCCESS = "FETCH_SUPPORT_BY_TOKEN_SUCCESS";
export const FETCH_SUPPORT_BY_TOKEN_FAILURE = "FETCH_SUPPORT_BY_TOKEN_FAILURE";
export const FETCH_SUPPORT_BY_TOKEN_PATH = "getAllSupport";

export const FETCH_SUPPORT_IMAGES = "FETCH_SUPPORT_IMAGES";
export const FETCH_SUPPORT_IMAGES_SUCCESS = "FETCH_SUPPORT_IMAGES_SUCCESS";
export const FETCH_SUPPORT_IMAGES_FAILURE = "FETCH_SUPPORT_IMAGES_FAILURE";
export const FETCH_SUPPORT_IMAGES_PATH = "getSupportImages";