export const GETALLREQUEST = "GETALLREQUEST";
export const GETALLREQUEST_SUCCESS = "GETALLREQUEST_SUCCESS";
export const GETALLREQUEST_FAILURE = "GETALLREQUEST_FAILURE";
export const GETALLREQUEST_PATH = "GetWalletRequests";

export const UPDATEREQUEST = "UPDATEREQUEST";
export const UPDATEREQUEST_SUCCESS = "UPDATEREQUEST_SUCCESS";
export const UPDATEREQUEST_FAILURE = "UPDATEREQUEST_FAILURE";
export const UPDATE_PATH = "GetWalletRequestsandUpdatepaymentbank";
