export const GET_PLOT_TRANSFER_REQ = "GET_PLOT_TRANSFER_REQ";
export const GET_PLOT_TRANSFER_REQ_SUCCESS = "GET_PLOT_TRANSFER_REQ_SUCCESS";
export const GET_PLOT_TRANSFER_REQ_FAILURE = "GET_PLOT_TRANSFER_REQ_FAILURE";
export const GET_PLOT_TRANSFER_REQ_PATH = "GetPlotTransferlogsforDocumentation";

export const GET_PLOT_TRANSFER_REQ_BY_ID = "GET_PLOT_TRANSFER_REQ_BY_ID";
export const GET_PLOT_TRANSFER_REQ_BY_ID_SUCCESS =
  "GET_PLOT_TRANSFER_REQ_BY_ID_SUCCESS";
export const GET_PLOT_TRANSFER_REQ_BY_ID_FAILURE =
  "GET_PLOT_TRANSFER_REQ_BY_ID_FAILURE";
export const GET_PLOT_TRANSFER_REQ_BY_ID_PATH = "GetRequestByidforDM";
