export const GET_PLOT_TRANSFER_REQ_MANAGER = "GET_PLOT_TRANSFER_REQ_MANAGER";
export const GET_PLOT_TRANSFER_REQ_MANAGER_SUCCESS =
  "GET_PLOT_TRANSFER_REQ_MANAGER_SUCCESS";
export const GET_PLOT_TRANSFER_REQ_MANAGER_FAILURE =
  "GET_PLOT_TRANSFER_REQ_MANAGER_FAILURE";
export const GET_PLOT_TRANSFER_REQ_MANAGER_PATH =
  "getPlotTransferlogsforDocumentManager";

export const PLOT_TRANSFER_REQ_APPROVAL = "PLOT_TRANSFER_REQ_APPROVAL";
export const PLOT_TRANSFER_REQ_APPROVAL_SUCCESS =
  "PLOT_TRANSFER_REQ_APPROVAL_SUCCESS";
export const PLOT_TRANSFER_REQ_APPROVAL_FAILURE =
  "PLOT_TRANSFER_REQ_APPROVAL_FAILURE";
export const PLOT_TRANSFER_REQ_APPROVAL_PATH = "requestforlastApprovalV2forDM";

export const GET_PLOT_TRANSFER_REQ_BY_ID = "GET_PLOT_TRANSFER_REQ_BY_ID";
export const GET_PLOT_TRANSFER_REQ_BY_ID_SUCCESS =
  "GET_PLOT_TRANSFER_REQ_BY_ID_SUCCESS";
export const GET_PLOT_TRANSFER_REQ_BY_ID_FAILURE =
  "GET_PLOT_TRANSFER_REQ_BY_ID_FAILURE";
export const GET_PLOT_TRANSFER_REQ_BY_ID_PATH = "GetRequestByidforDM";
