export const GET_DASHBOARD_WALLET = "GET_DASHBOARD_WALLET";

export const GET_DASHBOARD_WALLET_SUCCESS = "GET_DASHBOARD_WALLET_SUCCESS";

export const GET_DASHBOARD_WALLET_FAILURE = "GET_DASHBOARD_WALLET_FAILURE";

export const GET_DASHBOARD_WALLET_PATH = "FivependingRequests";

// Wallet user history

export const GET_WALLET_HISTORY = "GET_WALLET_HISTORY";

export const GET_WALLET_HISTORY_SUCCESS = "GET_WALLET_HISTORY_SUCCESS";

export const GET_WALLET_HISTORY_FAILURE = "GET_WALLET_HISTORY_FAILURE";

export const GET_WALLET_HISTORY_PATH = "GetTransactionhistoryByCnic";

// Approve or reject

export const UPDATEREQUEST = "UPDATEREQUEST";
export const UPDATEREQUEST_SUCCESS = "UPDATEREQUEST_SUCCESS";
export const UPDATEREQUEST_FAILURE = "UPDATEREQUEST_FAILURE";
export const UPDATE_PATH = "GetWalletRequestsandUpdatepaymentbank";
