export const PAYMENTDETAIL = "PAYMENTDETAIL";
export const PAYMENTDETAIL_SUCCESS = "PAYMENTDETAIL_SUCCESS";
export const PAYMENTDETAIL_FAILURE = "PAYMENTDETAIL_FAILURE";
export const PAYMENTDETAIL_PATH = "ViewPaymentStageDetails";

export const PAYMENTSTATUS = "PAYMENTSTATUS";
export const PAYMENTSTATUS_SUCCESS = "PAYMENTSTATUS_SUCCESS";
export const PAYMENTSTATUS_FAILURE = "PAYMENTSTATUS_FAILURE";
export const PAYMENTSTATUS_PATH = "ViewPaymentReceiptStatus";




export const PAYMENTERECIEPT = "PAYMENTERECIEPT";
export const PAYMENTERECIEPT_SUCCESS = "PAYMENTERECIEPT_SUCCESS";
export const PAYMENTERECIEPT_FAILURE = "PAYMENTERECIEPT_FAILURE";
export const PAYMENTERECIEPT_PATH = "PaymentEReceipt";

export const PAYMENTERECIEPTCOUNT = "PAYMENTERECIEPTCOUNT";
export const PAYMENTERECIEPTCOUNT_SUCCESS = "PAYMENTERECIEPTCOUNT_SUCCESS";
export const PAYMENTERECIEPTCOUNT_FAILURE = "PAYMENTERECIEPTCOUNT_FAILURE";
export const PAYMENTERECIEPTCOUNT_PATH = "getStatusCount/"; 