export const AllPROJECTSGRAPH= "AllPROJECTSGRAPH";
export const AllPROJECTSGRAPH_SUCCESS = "AllPROJECTSGRAPH_SUCCESS";
export const AllPROJECTSGRAPH_FAILURE = "AllPROJECTSGRAPH_FAILURE";
export const AllPROJECTSGRAPH_PATH = "PlotStats";

export const PROJECTREPORT= "PROJECTREPORT";
export const PROJECTREPORT_SUCCESS = "PROJECTREPORT_SUCCESS";
export const PROJECTREPORT_FAILURE = "PROJECTREPORT_FAILURE";
export const PROJECTREPORT_PATH = "DetailPlotInformation";

