export const AllCHANGEREQUEST = "AllCHANGEREQUEST";
export const AllCHANGEREQUEST_SUCCESS = "AllCHANGEREQUEST_SUCCESS";
export const AllCHANGEREQUEST_FAILURE = "AllCHANGEREQUEST_FAILURE";
export const AllCHANGEREQUEST_PATH = "getAllChangeRequests";


export const UPDATEAPPROVALSTATUS = "UPDATEAPPROVALSTATUS";
export const UPDATEAPPROVALSTATUS_SUCCESS = "UPDATEAPPROVALSTATUS_SUCCESS";
export const UPDATEAPPROVALSTATUS_FAILURE = "UPDATEAPPROVALSTATUS_FAILURE";
export const UPDATEAPPROVALSTATUS_PATH = "changeRequestStatus";

export const STATUS = "STATUS";
export const STATUS_SUCCESS = "STATUS_SUCCESS";
export const STATUS_FAILURE = "STATUS_FAILURE";
export const STATUS_PATH = "ChangePlotStatus";