export const APPROVALRECEIPT = "APPROVALRECEIPT";
export const APPROVALRECEIPT_SUCCESS = "APPROVALRECEIPT_SUCCESS";
export const APPROVALRECEIPT_FAILURE = "APPROVALRECEIPT_FAILURE";
export const APPROVALRECEIPT_PATH = "ViewPaymentApprovalReceipt";




export const UPDATEAPPROVALSTATUS = "UPDATEAPPROVALSTATUS";
export const UPDATEAPPROVALSTATUS_SUCCESS = "UPDATEAPPROVALSTATUS_SUCCESS";
export const UPDATEAPPROVALSTATUS_FAILURE = "UPDATEAPPROVALSTATUS_FAILURE";
export const UPDATEAPPROVALSTATUS_PATH = "UpdatePaymentReceiptStatus";


export const UPDATEPAYMENT = "UPDATEPAYMENT";
export const UPDATEPAYMENT_SUCCESS = "UPDATEPAYMENT_SUCCESS";
export const UPDATEPAYMENT_FAILURE = "UPDATEPAYMENT_FAILURE";
export const UPDATEPAYMENT_PATH = "UpdatePaymentReceiptCRM";


export const UPDATEPAYMENTSTAGESTATUS = "UPDATEPAYMENT";
export const UPDATEPAYMENTSTAGESTATUS_SUCCESS = "UPDATEPAYMENT_SUCCESS";
export const UPDATEPAYMENTSTAGESTATUS_FAILURE = "UPDATEPAYMENT_FAILURE";
export const UPDATEPAYMENTSTAGESTATUS_PATH = "UpdatePaymentStageStatus";
