export const GET_FILE_DOWNLOAD_CUSTOMER = "GET_FILE_DOWNLOAD_CUSTOMER";
export const GET_FILE_DOWNLOAD_CUSTOMER_SUCCESS =
  "GET_FILE_DOWNLOAD_CUSTOMER_SUCCESS";
export const GET_FILE_DOWNLOAD_CUSTOMER_FAILURE =
  "GET_FILE_DOWNLOAD_CUSTOMER_FAILURE";
export const GET_FILE_DOWNLOAD_CUSTOMER_PATH = "FileDownloadCustomers";

export const FILE_DOCUMENTS = "FILE_DOCUMENTS";
export const FILE_DOCUMENTS_SUCCESS = "FILE_DOCUMENTS_SUCCESS";
export const FILE_DOCUMENTS_FAILURE = "FILE_DOCUMENTS_FAILURE";
export const FILE_DOCUMENTS_PATH = "getFileDocuments";
