export const GET_COMPANY_WALLET = "GET_COMPANY_WALLET";

export const GET_COMPANY_WALLET_SUCCESS = "GET_COMPANY_WALLET_SUCCESS";

export const GET_COMPANY_WALLET_FAILURE = "GET_COMPANY_WALLET_FAILURE";

export const GET_COMPANY_WALLET_PATH = "CompanyWalletById";
