


export const UPDATE_PLOT_STATUS= "UPDATE_PLOT_STATUS";
export const UPDATE_PLOT_STATUS_SUCCESS = "UPDATE_PLOT_STATUS_SUCCESS";
export const UPDATE_PLOT_STATUS_FAILURE = "UPDATE_PLOT_STATUS_FAILURE";
export const UPDATE_PLOT_STATUS_PATH = "UpdatePlotStatus";

export const SALE_ORDER= "SALE_ORDER";
export const SALE_ORDER_SUCCESS = "SALE_ORDER_SUCCESS";
export const SALE_ORDER_FAILURE = "SALE_ORDER_FAILURE";
export const SALE_ORDER_PATH = "GetSaleOrder";
