version: 0.2
phases:
  install:
    commands:
      - echo runtime installed
      - n 10
  pre_build:
    commands:
      - echo installing source npm dependencies
      - npm install
  build:
    commands:
      - echo bilding
      - export NODE_OPTIONS="--max-old-space-size=3072"
      - npm run build
  post_build:
    commands:
      - echo build complete on `date`
      - aws s3 sync ./build s3://crm.squarepro.net/
      - aws cloudfront create-invalidation --distribution-id E3JU91HHRJ8AB0 --paths '/*'
