export const FETCH_AGENT_DETAILS = "FETCH_AGENT_DETAILS"
export const FETCH_AGENT_DETAILS_SUCCESS = "FETCH_AGENT_DETAILS_SUCCESS"
export const FETCH_AGENT_DETAILS_FAILURE = "FETCH_AGENT_DETAILS_FAILURE"
export const FETCH_AGENT_DETAILS_PATH = "getRealStateAgentDetails"

export const FETCH_ALL_VERIFIED_CUSTOMER = "FETCH_ALL_VERIFIED_CUSTOMER"
export const FETCH_ALL_VERIFIED_CUSTOMER_SUCCESS = "FETCH_ALL_VERIFIED_CUSTOMER_SUCCESS"
export const FETCH_ALL_VERIFIED_CUSTOMER_FAILURE = "FETCH_ALL_VERIFIED_CUSTOMER_FAILURE"
export const FETCH_ALL_VERIFIED_CUSTOMER_PATH = "VerifyDetails"

export const VERIFICATION_FORM = "VERIFICATION_FORM"
export const VERIFICATION_FORM_SUCCESS = "VERIFICATION_FORM_SUCCESS"
export const VERIFICATION_FORM_FAILURE = "VERIFICATION_FORM_FAILURE"
export const VERIFICATION_FORM_PATH = "BookingFormVerificationReceipt"