// SALE ORDER TYPE
export const SALE_ORDER = "SALE_ORDER";
export const SALE_ORDER_SUCCESS = "SALE_ORDER_SUCCESS";
export const SALE_ORDER_FAILURE = "SALE_ORDER_FAILURE";
//export const SALE_ORDER_PATH = "insertsaleorder";
export const SALE_ORDER_PATH = "createSaleOrder/v1";

// PAYMENT TYPE
export const PAYMENT_TYPE = "PAYMENT_TYPE";
export const PAYMENT_TYPE_SUCCESS = "PAYMENT_TYPE_SUCCESS";
export const PAYMENT_TYPE_FAILURE = "PAYMENT_TYPE_FAILURE";
export const PAYMENT_TYPE_PATH = "GetPaymentType";

// PAYMENT THROUGH
export const PAYMENT_THROUGH = "PAYMENT_THROUGH";
export const PAYMENT_THROUGH_SUCCESS = "PAYMENT_THROUGH_SUCCESS";
export const PAYMENT_THROUGH_FAILURE = "PAYMENT_THROUGH_FAILURE";
export const PAYMENT_THROUGH_PATH = "GetPaymentThrough";

// CURRENCY TYPE
export const CURRENCY_TYPE = "CURRENCY_TYPE";
export const CURRENCY_TYPE_SUCCESS = "CURRENCY_TYPE_SUCCESS";
export const CURRENCY_TYPE_FAILURE = "CURRENCY_TYPE_FAILURE";
export const CURRENCY_TYPE_PATH = "GetCurrencyType";

export const PAYMENT_SCHEDULE = "PAYMENT_SCHEDULE";
export const PAYMENT_SCHEDULE_SUCCESS = "PAYMENT_SCHEDULE_SUCCESS";
export const PAYMENT_SCHEDULE_FAILURE = "PAYMENT_SCHEDULE_FAILURE";
//export const PAYMENT_SCHEDULE_PATH = "GetPaymentSchedule";
export const PAYMENT_SCHEDULE_PATH = "GetStandardPlans";

export const SHORT_PAYMENT_SCHEDULE = "SHORT_PAYMENT_SCHEDULE";
export const SHORT_PAYMENT_SCHEDULE_SUCCESS = "SHORT_PAYMENT_SCHEDULE_SUCCESS";
export const SHORT_PAYMENT_SCHEDULE_FAILURE = "SHORT_PAYMENT_SCHEDULE_FAILURE";
//export const SHORT_PAYMENT_SCHEDULE_PATH = "GetShortPaymentSchedule";
export const SHORT_PAYMENT_SCHEDULE_PATH = "ViewPaymentSchedule";

export const PAYMENT_STAGES = "PAYMENT_STAGES";
export const PAYMENT_STAGES_SUCCESS = "PAYMENT_STAGES_SUCCESS";
export const PAYMENT_STAGES_FAILURE = "PAYMENT_STAGES_FAILURE";
export const PAYMENT_STAGES_PATH = "InserPaymentStages";

export const CUSTOM_PLAN_GENERATE = "CUSTOM_PLAN_GENERATE";
export const CUSTOM_PLAN_GENERATE_SUCCESS = "CUSTOM_PLAN_GENERATE_SUCCESS";
export const CUSTOM_PLAN_GENERATE_FAILURE = "CUSTOM_PLAN_GENERATE_FAILURE";
//export const CUSTOM_PLAN_GENERATE_PATH = "ViewCustomSchedule";
export const CUSTOM_PLAN_GENERATE_PATH = "createSaleOrder/v1";

export const PRINT_SALEORDER_PLAN = "PRINT_SALEORDER_PLAN";
export const PRINT_SALEORDER_PLAN_SUCCESS = "PRINT_SALEORDER_PLAN_SUCCESS";
export const PRINT_SALEORDER_PLAN_FAILURE = "PRINT_SALEORDER_PLAN_FAILURE";
export const PRINT_SALEORDER_PLAN_PATH = "ViewStandardPlan";

export const PRINT_FULL_SALEORDER_PLAN = "PRINT_FULL_SALEORDER_PLAN";
export const PRINT_FULL_SALEORDER_PLAN_SUCCESS =
  "PRINT_FULL_SALEORDER_PLAN_SUCCESS";
export const PRINT_FULL_SALEORDER_PLAN_FAILURE =
  "PRINT_FULL_SALEORDER_PLAN_FAILURE";
export const PRINT_FULL_SALEORDER_PLAN_PATH = "ViewFullpaymentPlan";

export const PRINT_CUSTOM_PLAN = "PRINT_CUSTOM_PLAN";
export const PRINT_CUSTOM_PLAN_SUCCESS = "PRINT_CUSTOM_PLAN_SUCCESS";
export const PRINT_CUSTOM_PLAN_FAILURE = "PRINT_CUSTOM_PLAN_FAILURE";
export const PRINT_CUSTOM_PLAN_PATH = "ViewCustomPlan";
