export const GET_SALE_ORDER = "GET_SALE_ORDER";
export const GET_SALE_ORDER_SUCCESS = "GET_SALE_ORDER_SUCCESS";
export const GET_SALE_ORDER_FAILURE = "GET_SALE_ORDER_FAILURE";
export const GET_SALE_ORDER_PATH = "GetSaleOrder";

export const GET_PAYMENT_STAGES = "GET_PAYMENT_STAGES";
export const GET_PAYMENT_STAGES_SUCCESS = "GET_PAYMENT_STAGES_SUCCESS";
export const GET_PAYMENT_STAGES_FAILURE = "GET_PAYMENT_STAGES_FAILURE";
export const GET_PAYMENT_STAGES_PATH = "GetPaymentStages";

export const GET_FULL_PAYMENT_STAGES = "GET_FULL_PAYMENT_STAGES";
export const GET_FULL_PAYMENT_STAGES_SUCCESS =
  "GET_FULL_PAYMENT_STAGES_SUCCESS";
export const GET_FULL_PAYMENT_STAGES_FAILURE =
  "GET_FULL_PAYMENT_STAGES_FAILURE";
export const GET_FULL_PAYMENT_STAGES_PATH = "GetSaleorderwithstages";

export const GET_PAYMENT_SCHEDULE = "GET_PAYMENT_SCHEDULE";
export const GET_PAYMENT_SCHEDULE_SUCCESS = "GET_PAYMENT_SCHEDULE_SUCCESS";
export const GET_PAYMENT_SCHEDULE_FAILURE = "GET_PAYMENT_SCHEDULE_FAILURE";
export const GET_PAYMENT_SCHEDULE_PATH = "printPaymentSchedule";

export const GET_SALE_ORDER_BY_ID = "GET_SALE_ORDER_BY_ID";
export const GET_SALE_ORDER_BY_ID_SUCCESS = "GET_SALE_ORDER_BY_ID_SUCCESS";
export const GET_SALE_ORDER_BY_ID_FAILURE = "GET_SALE_ORDER_BY_ID_FAILURE";
export const GET_SALE_ORDER_BY_ID_PATH = "GetSaleOrderById";

export const GET_RECIEPT_BY_ID = "GET_RECIEPT_BY_ID";
export const GET_RECIEPT_BY_ID_SUCCESS = "GET_RECIEPT_BY_ID_SUCCESS";
export const GET_RECIEPT_BY_ID_FAILURE = "GET_RECIEPT_BY_ID_FAILURE";
export const GET_RECIEPT_BY_ID_PATH = "GetRecieptDetailsById";