export const REALSTATEAGENTDETAIL = "REALSTATEAGENTDETAIL";
export const REALSTATEAGENTDETAIL_SUCCESS = "REALSTATEAGENTDETAIL_SUCCESS";
export const REALSTATEAGENTDETAIL_FAILURE = "REALSTATEAGENTDETAIL_FAILURE";
export const REALSTATEAGENTDETAIL_PATH = "getRealStateAgentDetails";

export const BOOKINGFORMSTATUS = "BOOKINGFORMSTATUS";
export const BOOKINGFORMSTATUS_SUCCESS = "BOOKINGFORMSTATUS_SUCCESS";
export const BOOKINGFORMSTATUS_FAILURE = "BOOKINGFORMSTATUS_FAILURE";
export const BOOKINGFORMSTATUS_PATH = "GetBookingFormStatus";

export const UPGRADE_FORM_STATUS = "UPGRADE_FORM_STATUS";
export const UPGRADE_FORM_STATUS_SUCCESS = "UPGRADE_FORM_STATUS_SUCCESS";
export const UPGRADE_FORM_STATUS_FAILURE = "UPGRADE_FORM_STATUS_FAILURE";
export const UPGRADE_FORM_STATUS_PATH = "UpgradeFormStatus";

export const UPLOAD_CURRENCY = "UPLOAD_CURRENCY";
export const UPLOAD_CURRENCY_SUCCESS = "UPLOAD_CURRENCY_SUCCESS";
export const UPLOAD_CURRENCY_FAILURE = "UPLOAD_CURRENCY_FAILURE";
export const UPLOAD_CURRENCY_PATH = "addNotes";
