

export const PROJECTFILE= "PROJECTFILE";
export const PROJECTFILE_SUCCESS = "PROJECTFILE_SUCCESS";
export const PROJECTFILE_FAILURE = "PROJECTFILE_FAILURE";
export const PROJECTFILE_PATH = "AddProjectFile";

