export const AMOUNT = "AMOUNT";
export const AMOUNT_SUCCESS = "AMOUNT_SUCCESS";
export const AMOUNT_FAILURE = "AMOUNT_FAILURE";
export const AMOUNT_PATH = "GetCurrencyType";

export const PAYMENTTHROUGH = "PAYMENTTHROUGH";
export const PAYMENTTHROUGH_SUCCESS = "PAYMENTTHROUGH_SUCCESS";
export const PAYMENTTHROUGH_FAILURE = "PAYMENTTHROUGH_FAILURE";
export const PAYMENTTHROUGH_PATH = "GetPaymentThrough";

export const PAYMENTTYPE = "PAYMENTTYPE";
export const PAYMENTTYPE_SUCCESS = "PAYMENTTYPE_SUCCESS";
export const PAYMENTTYPE_FAILURE = "PAYMENTTYPE_FAILURE";
export const PAYMENTTYPE_PATH = "GetPaymentType";

export const PAYMENT_RECIPT = "PAYMENT_RECIPT";
export const PAYMENT_RECIPT_SUCCESS = "PAYMENT_RECIPT_SUCCESS";
export const PAYMENT_RECIPT_FAILURE = "PAYMENT_RECIPT_FAILURE";
export const PAYMENT_RECIPT_PATH = "InserPaymentReceipt";

export const UPDATE_PAYMENT_STAGE = "UPDATE_PAYMENT_STAGE";
export const UPDATE_PAYMENT_STAGE_SUCCESS = "UPDATE_PAYMENT_STAGE_SUCCESS";
export const UPDATE_PAYMENT_STAGE_FAILURE = "UPDATE_PAYMENT_STAGE_FAILURE";
export const UPDATE_PAYMENT_STAGE_PATH = "UpdatePaymentStageStatus";

export const WALLET = "WALLET";
export const WALLET_SUCCESS = "WALLET_SUCCESS";
export const WALLET_FAILURE = "WALLET_FAILURE";
export const WALLET_PATH = "InsertCustomerWallet";

export const WALLET_REQUEST = "WALLET_REQUEST";
export const WALLET_REQUEST_SUCCESS = "WALLET_REQUEST_SUCCESS";
export const WALLET_REQUEST_FAILURE = "WALLET_REQUEST_FAILURE";
export const WALLET_REQUEST_PATH = "AddWalletRequest";

export const FILE = "FILE";
export const FILE_SUCCESS = "FILE_SUCCESS";
export const FILE_FAILURE = "FILE_FAILURE";
export const FILE_PATH = "postDocument";

export const BANK = "BANK";
export const BANK_SUCCESS = "BANK_SUCCESS";
export const BANK_FAILURE = "BANK_FAILURE";
export const BANK_PATH = "getBanks";
