export const GET_PLOT_CANCEL_REQUEST_AGENT = "GET_PLOT_CANCEL_REQUEST_AGENT";
export const GET_PLOT_CANCEL_REQUEST_AGENT_SUCCESS =
  "GET_PLOT_CANCEL_REQUEST_AGENT_SUCCESS";
export const GET_PLOT_CANCEL_REQUEST_AGENT_FAILURE =
  "GET_PLOT_CANCEL_REQUEST_AGENT_FAILURE";
export const GET_PLOT_CANCEL_REQUEST_AGENT_PATH = "GetPlotReturnRequests";

export const GET_PLOT_CANCEL_REQUEST_AGENT_ID =
  "GET_PLOT_CANCEL_REQUEST_AGENT_ID";
export const GET_PLOT_CANCEL_REQUEST_AGENT_ID_SUCCESS =
  "GET_PLOT_CANCEL_REQUEST_AGENT_ID_SUCCESS";
export const GET_PLOT_CANCEL_REQUEST_AGENT_ID_FAILURE =
  "GET_PLOT_CANCEL_REQUEST_AGENT_ID_FAILURE";
export const GET_PLOT_CANCEL_REQUEST_AGENT_ID_PATH = "";

export const GET_REFUND_LIST_AGENT = "GET_REFUND_LIST_AGENT";
export const GET_REFUND_LIST_AGENT_SUCCESS = "GET_REFUND_LIST_AGENT_SUCCESS";
export const GET_REFUND_LIST_AGENT_FAILURE = "GET_REFUND_LIST_AGENT_FAILURE";
export const GET_REFUND_LIST_AGENT_PATH = "getRefundStages";

export const UPDATE_REFUND_LIST_AGENT = "UPDATE_REFUND_LIST_AGENT";
export const UPDATE_REFUND_LIST_AGENT_SUCCESS =
  "UPDATE_REFUND_LIST_AGENT_SUCCESS";
export const UPDATE_REFUND_LIST_AGENT_FAILURE =
  "UPDATE_REFUND_LIST_AGENT_FAILURE";
export const UPDATE_REFUND_LIST_AGENT_PATH = "payRefundStage";
