export const GET_ALL_SALEORDER = "GET_ALL_SALEORDER";
export const GET_ALL_SALEORDER_SUCCESS = "GET_ALL_SALEORDER_SUCCESS";
export const GET_ALL_SALEORDER_FAILURE = "GET_ALL_SALEORDER_FAILURE";
export const GET_ALL_SALEORDER_PATH = "GetSaleOrder";

export const SALEORDER_DETAILS = "SALEORDER_DETAILS";
export const SALEORDER_DETAILS_SUCCESS = "SALEORDER_DETAILS_SUCCESS";
export const SALEORDER_DETAILS_FAILURE = "SALEORDER_DETAILS_FAILURE";
export const SALEORDER_DETAILS_PATH = "GetSellQuotationStatus";