// PAYMENT SCHEDULES
export const GET_PAYMENT_SCHEDULE = "GET_PAYMENT_SCHEDULE";
export const GET_PAYMENT_SCHEDULE_SUCCESS = "GET_PAYMENT_SCHEDULE_SUCCESS";
export const GET_PAYMENT_SCHEDULE_FAILURE = "GET_PAYMENT_SCHEDULE_FAILURE";
export const GET_PAYMENT_SCHEDULE_PATH = "GetAllpaymentplan";

export const ADD_PAYMENT_SCHEDULE = "ADD_PAYMENT_SCHEDULE";
export const ADD_PAYMENT_SCHEDULE_SUCCESS = "ADD_PAYMENT_SCHEDULE_SUCCESS";
export const ADD_PAYMENT_SCHEDULE_FAILURE = "ADD_PAYMENT_SCHEDULE_FAILURE";
export const ADD_PAYMENT_SCHEDULE_PATH = "InsertPaymentplan";

export const UPDATE_SCHEDULE = "UPDATE_SCHEDULE";
export const UPDATE_SCHEDULE_SUCCESS = "UPDATE_SCHEDULE_SUCCESS";
export const UPDATE_SCHEDULE_FAILURE = "UPDATE_SCHEDULE_FAILURE";
export const UPDATE_SCHEDULE_PATH = "UpdatePaymentplan";

// PROJECTS

export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE";
export const GET_PROJECT_PATH = "GetAllProjects";

export const ADD_PROJECT = "ADD_PROJECT";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const ADD_PROJECT_FAILURE = "ADD_PROJECT_FAILURE";
export const ADD_PROJECT_PATH = "AddProject";

export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";
export const UPDATE_PROJECT_PATH = "UpdateProject";

// SECTORS

export const GET_SECTORS = "GET_SECTORS";
export const GET_SECTORS_SUCCESS = "GET_SECTORS_SUCCESS";
export const GET_SECTORS_FAILURE = "GET_SECTORS_FAILURE";
export const GET_SECTORS_PATH = "GetAllsectors";

export const ADD_SECTORS = "ADD_SECTORS";
export const ADD_SECTORS_SUCCESS = "ADD_SECTORS_SUCCESS";
export const ADD_SECTORS_FAILURE = "ADD_SECTORS_FAILURE";
export const ADD_SECTORS_PATH = "AddSector";

export const UPDATE_SECTORS = "UPDATE_SECTORS";
export const UPDATE_SECTORS_SUCCESS = "UPDATE_SECTORS_SUCCESS";
export const UPDATE_SECTORS_FAILURE = "UPDATE_SECTORS_FAILURE";
export const UPDATE_SECTORS_PATH = "UpdateSector";

// STREETS

export const GET_STREETS = "GET_STREETS";
export const GET_STREETS_SUCCESS = "GET_STREETS_SUCCESS";
export const GET_STREETS_FAILURE = "GET_STREETS_FAILURE";
export const GET_STREETS_PATH = "GetAllstreets";

export const ADD_STREETS = "ADD_STREETS";
export const ADD_STREETS_SUCCESS = "ADD_STREETS_SUCCESS";
export const ADD_STREETS_FAILURE = "ADD_STREETS_FAILURE";
export const ADD_STREETS_PATH = "AddStreet";

export const UPDATE_STREETS = "UPDATE_STREETS";
export const UPDATE_STREETS_SUCCESS = "UPDATE_STREETS_SUCCESS";
export const UPDATE_STREETS_FAILURE = "UPDATE_STREETS_FAILURE";
export const UPDATE_STREETS_PATH = "UpdateStreet";
