export const GET_PLOT_CANCEL_REQUEST_ACCOUNTS =
  "GET_PLOT_CANCEL_REQUEST_ACCOUNTS";
export const GET_PLOT_CANCEL_REQUEST_ACCOUNTS_SUCCESS =
  "GET_PLOT_CANCEL_REQUEST_ACCOUNTS_SUCCESS";
export const GET_PLOT_CANCEL_REQUEST_ACCOUNTS_FAILURE =
  "GET_PLOT_CANCEL_REQUEST_ACCOUNTS_FAILURE";
export const GET_PLOT_CANCEL_REQUEST_ACCOUNTS_PATH = "GetPlotReturnRequests";

export const GET_PLOT_CANCEL_REQUEST_ACCOUNTS_ID =
  "GET_PLOT_CANCEL_REQUEST_ACCOUNTS_ID";
export const GET_PLOT_CANCEL_REQUEST_ACCOUNTS_ID_SUCCESS =
  "GET_PLOT_CANCEL_REQUEST_ACCOUNTS_ID_SUCCESS";
export const GET_PLOT_CANCEL_REQUEST_ACCOUNTS_ID_FAILURE =
  "GET_PLOT_CANCEL_REQUEST_ACCOUNTS_ID_FAILURE";
export const GET_PLOT_CANCEL_REQUEST_ACCOUNTS_ID_PATH = "";

export const PLOT_CANCEL_REQ_APPROVAL = "PLOT_CANCEL_REQ_APPROVAL";
export const PLOT_CANCEL_REQ_APPROVAL_SUCCESS =
  "PLOT_CANCEL_REQ_APPROVAL_SUCCESS";
export const PLOT_CANCEL_REQ_APPROVAL_FAILURE =
  "PLOT_CANCEL_REQ_APPROVAL_FAILURE";
export const PLOT_CANCEL_REQ_APPROVAL_PATH = "ReturnRequestApproval";
