export const GET_PLOT_CANCEL_REQUEST_MANAGER =
  "GET_PLOT_CANCEL_REQUEST_MANAGER";
export const GET_PLOT_CANCEL_REQUEST_MANAGER_SUCCESS =
  "GET_PLOT_CANCEL_REQUEST_MANAGER_SUCCESS";
export const GET_PLOT_CANCEL_REQUEST_MANAGER_FAILURE =
  "GET_PLOT_CANCEL_REQUEST_MANAGER_FAILURE";
export const GET_PLOT_CANCEL_REQUEST_MANAGER_PATH = "GetPlotReturnRequests";

export const GET_PLOT_CANCEL_REQUEST_MANAGER_ID =
  "GET_PLOT_CANCEL_REQUEST_MANAGER_ID";
export const GET_PLOT_CANCEL_REQUEST_MANAGER_ID_SUCCESS =
  "GET_PLOT_CANCEL_REQUEST_MANAGER_ID_SUCCESS";
export const GET_PLOT_CANCEL_REQUEST_MANAGER_ID_FAILURE =
  "GET_PLOT_CANCEL_REQUEST_MANAGER_ID_FAILURE";
export const GET_PLOT_CANCEL_REQUEST_MANAGER_ID_PATH = "";

export const PLOT_CANCEL_REQ_APPROVAL = "PLOT_CANCEL_REQ_APPROVAL";
export const PLOT_CANCEL_REQ_APPROVAL_SUCCESS =
  "PLOT_CANCEL_REQ_APPROVAL_SUCCESS";
export const PLOT_CANCEL_REQ_APPROVAL_FAILURE =
  "PLOT_CANCEL_REQ_APPROVAL_FAILURE";
export const PLOT_CANCEL_REQ_APPROVAL_PATH = "ReturnRequestApproval";
