export const GET_ALL_QUOTATION = "GET_ALL_QUOTATION";
export const GET_ALL_QUOTATION_SUCCESS = "GET_ALL_QUOTATION_SUCCESS";
export const GET_ALL_QUOTATION_FAILURE = "GET_ALL_QUOTATION_FAILURE";
export const GET_ALL_QUOTATION_PATH = "GetQuatation";

export const QUOTATION_DETAILS = "QUOTATION_DETAILS";
export const QUOTATION_DETAILS_SUCCESS = "QUOTATION_DETAILS_SUCCESS";
export const QUOTATION_DETAILS_FAILURE = "QUOTATION_DETAILS_FAILURE";
export const QUOTATION_DETAILS_PATH = "GetSellQuotationStatus";

export const UPDATE_DETAILS = "UPDATE_DETAILS";
export const UPDATE_DETAILS_SUCCESS = "UPDATE_DETAILS_SUCCESS";
export const UPDATE_DETAILS_FAILURE = "UPDATE_DETAILS_FAILURE";
export const UPDATE_DETAILS_PATH = "sellplot";
