export const PLOTRETURN = "PLOTRETURN";
export const PLOTRETURN_SUCCESS = "PLOTRETURN_SUCCESS";
export const PLOTRETURN_FAILURE = "PLOTRETURN_FAILURE";
export const PLOTRETURN_PATH = "GetChangePlotReturnRequest";

export const PLOTINFO = "PLOTINFO";
export const PLOTINFO_SUCCESS = "PLOTINFO_SUCCESS";
export const PLOTINFO_FAILURE = "PLOTINFO_FAILURE";
export const PLOTINFO_PATH = "GetReturnPlotDetails";


export const UPDATEPLOTRETURNREQ = "UPDATEPLOTRETURNREQ";
export const UPDATEPLOTRETURNREQ_SUCCESS = "UPDATEPLOTRETURNREQ_SUCCESS";
export const UPDATEPLOTRETURNREQ_FAILURE = "UPDATEPLOTRETURNREQ_FAILURE";
export const UPDATEPLOTRETURNREQ_PATH = "UpdatePlotReturnRequestStatus";