export const ORDER_STATUS = "ORDER_STATUS";
export const ORDER_STATUS_SUCCESS = "ORDER_STATUS_SUCCESS";
export const ORDER_STATUS_FAILURE = "ORDER_STATUS_FAILURE";
export const ORDER_STATUS_PATH = "ShowAllOrderstatus";
