export const VERIFICATIONNO = "VERIFICATIONNO";
export const VERIFICATIONNO_SUCCESS = "VERIFICATIONNO_SUCCESS";
export const VERIFICATIONNO_FAILURE = "VERIFICATIONNO_FAILURE";
export const VERIFICATIONNO_PATH = "SaveVarificationForms";

export const INSERT_VERIFICATION_DATA = "INSERT_VERIFICATION_DATA";
export const INSERT_VERIFICATION_DATA_SUCCESS =
  "INSERT_VERIFICATION_DATA_SUCCESS";
export const INSERT_VERIFICATION_DATA_FAILURE =
  "INSERT_VERIFICATION_DATA_FAILURE";
export const INSERT_VERIFICATION_DATA_PATH = "UpdateVerificationNote ";
