export const CUSTOMER_DATA = "CUSTOMER_DATA";
export const CUSTOMER_DATA_SUCCESS = "CUSTOMER_DATA_SUCCESS";
export const CUSTOMER_DATA_FAILURE = "CUSTOMER_DATA_FAILURE";
export const CUSTOMER_DATA_PATH = "#";
