export const REALSTATEAGENT = "REALSTATEAGENT";
export const REALSTATEAGENT_SUCCESS = "REALSTATEAGENT_SUCCESS";
export const REALSTATEAGENT_FAILURE = "REALSTATEAGENT_FAILURE";
export const REALSTATEAGENT_PATH = "createRealStateAgent";

export const NOTES_STATUS = "NOTES_STATUS";
export const NOTES_STATUS_SUCCESS = "NOTES_STATUS_SUCCESS";
export const NOTES_STATUS_FAILURE = "NOTES_STATUS_FAILURE";
export const NOTES_STATUS_PATH = "getNotesStats";