export const ADD_NEW_ROLE = "ADD_NEW_ROLE";
export const ADD_NEW_ROLE_SUCCESS = "ADD_NEW_ROLE_SUCESS";
export const ADD_NEW_ROLE_FAILURE = "ADD_NEW_ROLE_FALURE";
export const ADD_NEW_ROLE_PATH = "Createrole";

export const UPDATE_CREATE_ASSIGN_MODULE = "UPDATE_CREATE_ASSIGN_MODULE";
export const UPDATE_CREATE_ASSIGN_MODULE_SUCCESS =
  "UPDATE_CREATE_ASSIGN_MODULE_SUCESS";
export const UPDATE_CREATE_ASSIGN_MODULE_FAILURE =
  "UPDATE_CREATE_ASSIGN_MODULE_FALURE";
export const UPDATE_CREATE_ASSIGN_MODULE_PATH = "updateAndcreateAssignModules";

export const FETCH_ROLES = "FETCH_ROLES";
export const FETCH_ROLES_SUCCESS = "FETCH_ROLES_SUCCESS";
export const FETCH_ROLES_FAILURE = "FETCH_ROLES_FAILURE";
export const FETCH_ROLES_PATH = "getAllRolesofCrm";

export const FETCH_ALL_APP_MODULES = "FETCH_ALL_APP_MODULES";
export const FETCH_ALL_APP_MODULES_SUCCESS = "FETCH_ALL_APP_MODULES_SUCCESS";
export const FETCH_ALL_APP_MODULES_FAILURE = "FETCH_ALL_APP_MODULES_FAILURE";
export const FETCH_ALL_APP_MODULES_PATH = "getAllAppModule";

export const FETCH_ALL_ASSIGN_MODULES = "FETCH_ALL_ASSIGN_MODULES";
export const FETCH_ALL_ASSIGN_MODULES_SUCCESS =
  "FETCH_ALL_ASSIGN_MODULES_SUCCESS";
export const FETCH_ALL_ASSIGN_MODULES_FAILURE =
  "FETCH_ALL_ASSIGN_MODULES_FAILURE";
export const FETCH_ALL_ASSIGN_MODULES_PATH = "getAllAssignModulesofCrm";
