export const GET_SUPPORT_CONVERSATION_SUCCESS =
  "GET_SUPPORT_CONVERSATION_SUCCESS";

export const GET_SUPPORT_CONVERSATION_BY_ID_SUCCESS =
  "GET_SUPPORT_CONVERSATION_BY_ID_SUCCESS";

export const SUPPORT_CONVERSATION_ENDPOINT = "v1/support-conversation";

export const SUPPORT_CHAT_SEND_BY_ADMIN_SUCCESS =
  "SUPPORT_CHAT_SEND_BY_ADMIN_SUCCESS";

export const SUPPORT_CHAT_SEND_BY_ADMIN_ENDPOINT = "support-chat/send-by-admin";
