//PLOT TYPE
export const GET_PLOT_TYPE_SUCCESS = "GET_PLOT_TYPE_SUCCESS";

export const CREATE_PLOT_TYPE_SUCCESS = "CREATE_PLOT_TYPE_SUCCESS";

export const DELETE_PLOT_TYPE_SUCCESS = "DELETE_PLOT_TYPE_SUCCESS";

export const EDIT_PLOT_TYPE_SUCCESS = "EDIT_PLOT_TYPE_SUCCESS";

export const PLOT_TYPE_ENDPOINT = "v1/plot-type";

//PLOT CATEGORY
export const GET_PLOT_CATEGORY_SUCCESS = "GET_PLOT_CATEGORY_SUCCESS";

export const CREATE_PLOT_CATEGORY_SUCCESS = "CREATE_PLOT_CATEGORY_SUCCESS";

export const DELETE_PLOT_CATEGORY_SUCCESS = "DELETE_PLOT_CATEGORY_SUCCESS";

export const EDIT_PLOT_CATEGORY_SUCCESS = "EDIT_PLOT_CATEGORY_SUCCESS";

export const PLOT_CATEGORY_ENDPOINT = "v1/plot-category";

//PLOT POSITION
export const GET_PLOT_POSITION_SUCCESS = "GET_PLOT_POSITION_SUCCESS";

export const CREATE_PLOT_POSITION_SUCCESS = "CREATE_PLOT_POSITION_SUCCESS";

export const DELETE_PLOT_POSITION_SUCCESS = "DELETE_PLOT_POSITION_SUCCESS";

export const EDIT_PLOT_POSITION_SUCCESS = "EDIT_PLOT_POSITION_SUCCESS";

export const PLOT_POSITION_ENDPOINT = "v1/plot-position";

//PLOT SECTOR
export const GET_PLOT_SECTOR_SUCCESS = "GET_PLOT_SECTOR_SUCCESS";

export const CREATE_PLOT_SECTOR_SUCCESS = "CREATE_PLOT_SECTOR_SUCCESS";

export const DELETE_PLOT_SECTOR_SUCCESS = "DELETE_PLOT_SECTOR_SUCCESS";

export const EDIT_PLOT_SECTOR_SUCCESS = "EDIT_PLOT_SECTOR_SUCCESS";

export const PLOT_SECTOR_ENDPOINT = "v1/plot-sector";

//PLOT STREET
export const GET_PLOT_STREET_SUCCESS = "GET_PLOT_STREET_SUCCESS";

export const CREATE_PLOT_STREET_SUCCESS = "CREATE_PLOT_STREET_SUCCESS";

export const DELETE_PLOT_STREET_SUCCESS = "DELETE_PLOT_STREET_SUCCESS";

export const EDIT_PLOT_STREET_SUCCESS = "EDIT_PLOT_STREET_SUCCESS";

export const PLOT_STREET_ENDPOINT = "v1/plot-street";

//PROJECT MAIN FEATURE
export const GET_PROJECT_MAIN_FEATURE_SUCCESS =
  "GET_PROJECT_MAIN_FEATURE_SUCCESS";

export const CREATE_PROJECT_MAIN_FEATURE_SUCCESS =
  "CREATE_PROJECT_MAIN_FEATURE_SUCCESS";

export const DELETE_PROJECT_MAIN_FEATURE_SUCCESS =
  "DELETE_PROJECT_MAIN_FEATURE_SUCCESS";

export const EDIT_PROJECT_MAIN_FEATURE_SUCCESS =
  "EDIT_PROJECT_MAIN_FEATURE_SUCCESS";

export const PROJECT_MAIN_FEATURE_ENDPOINT = "v1/project-main-feature";

//PROJECT COMMUNITY FEATURE
export const GET_PROJECT_COMMUNITY_FEATURE_SUCCESS =
  "GET_PROJECT_COMMUNITY_FEATURE_SUCCESS";

export const CREATE_PROJECT_COMMUNITY_FEATURE_SUCCESS =
  "CREATE_PROJECT_COMMUNITY_FEATURE_SUCCESS";

export const DELETE_PROJECT_COMMUNITY_FEATURE_SUCCESS =
  "DELETE_PROJECT_COMMUNITY_FEATURE_SUCCESS";

export const EDIT_PROJECT_COMMUNITY_FEATURE_SUCCESS =
  "EDIT_PROJECT_COMMUNITY_FEATURE_SUCCESS";

export const PROJECT_COMMUNITY_FEATURE_ENDPOINT =
  "v1/project-community-feature";

//PROJECT PLOT FEATURE
export const GET_PROJECT_PLOT_FEATURE_SUCCESS =
  "GET_PROJECT_PLOT_FEATURE_SUCCESS";

export const CREATE_PROJECT_PLOT_FEATURE_SUCCESS =
  "CREATE_PROJECT_PLOT_FEATURE_SUCCESS";

export const DELETE_PROJECT_PLOT_FEATURE_SUCCESS =
  "DELETE_PROJECT_PLOT_FEATURE_SUCCESS";

export const EDIT_PROJECT_PLOT_FEATURE_SUCCESS =
  "EDIT_PROJECT_PLOT_FEATURE_SUCCESS";

export const PROJECT_PLOT_FEATURE_ENDPOINT = "v1/project-plot-feature";

//PROJECT OTHER FEATURE
export const GET_PROJECT_OTHER_FEATURE_SUCCESS =
  "GET_PROJECT_OTHER_FEATURE_SUCCESS";

export const CREATE_PROJECT_OTHER_FEATURE_SUCCESS =
  "CREATE_PROJECT_OTHER_FEATURE_SUCCESS";

export const DELETE_PROJECT_OTHER_FEATURE_SUCCESS =
  "DELETE_PROJECT_OTHER_FEATURE_SUCCESS";

export const EDIT_PROJECT_OTHER_FEATURE_SUCCESS =
  "EDIT_PROJECT_OTHER_FEATURE_SUCCESS";

export const PROJECT_OTHER_FEATURE_ENDPOINT = "v1/project-other-feature";

//PROJECT RECREATIONAL
export const GET_PROJECT_RECREATIONAL_SUCCESS =
  "GET_PROJECT_RECREATIONAL_SUCCESS";

export const CREATE_PROJECT_RECREATIONAL_SUCCESS =
  "CREATE_PROJECT_RECREATIONAL_SUCCESS";

export const DELETE_PROJECT_RECREATIONAL_SUCCESS =
  "DELETE_PROJECT_RECREATIONAL_SUCCESS";

export const EDIT_PROJECT_RECREATIONAL_SUCCESS =
  "EDIT_PROJECT_RECREATIONAL_SUCCESS";

export const PROJECT_RECREATIONAL_ENDPOINT = "v1/project-recreational";

//PROJECT NEARBY LOCATION
export const GET_PROJECT_NEARBY_LOCATION_SUCCESS =
  "GET_PROJECT_NEARBY_LOCATION_SUCCESS";

export const CREATE_PROJECT_NEARBY_LOCATION_SUCCESS =
  "CREATE_PROJECT_NEARBY_LOCATION_SUCCESS";

export const DELETE_PROJECT_NEARBY_LOCATION_SUCCESS =
  "DELETE_PROJECT_NEARBY_LOCATION_SUCCESS";

export const EDIT_PROJECT_NEARBY_LOCATION_SUCCESS =
  "EDIT_PROJECT_NEARBY_LOCATION_SUCCESS";

export const PROJECT_NEARBY_LOCATION_ENDPOINT = "v1/project-near-by-location";

//COUNTRY
export const GET_COUNTRY_SUCCESS = "GET_COUNTRY_SUCCESS";

export const COUNTRY_ENDPOINT = "v1/country";

//CITY BY COUNTRY ID
export const GET_CITY_BY_COUNTRY_ID_SUCCESS = "GET_CITY_BY_COUNTRY_ID_SUCCESS";

export const CITY_BY_COUNTRY_ID_ENDPOINT = "v1/city/by-country-id";
