export const GET_PLOT_TRANSFER_REQ_FINANCE = "GET_PLOT_TRANSFER_REQ_FINANCE";
export const GET_PLOT_TRANSFER_REQ_FINANCE_SUCCESS =
  "GET_PLOT_TRANSFER_REQ_FINANCE_SUCCESS";
export const GET_PLOT_TRANSFER_REQ_FINANCE_FAILURE =
  "GET_PLOT_TRANSFER_REQ_FINANCE_FAILURE";
export const GET_PLOT_TRANSFER_REQ_FINANCE_PATH =
  "GetPlotTransferlogsforAccounts";

export const PLOT_TRANSFER_REQ_APPROVAL = "PLOT_TRANSFER_REQ_APPROVAL";
export const PLOT_TRANSFER_REQ_APPROVAL_SUCCESS =
  "PLOT_TRANSFER_REQ_APPROVAL_SUCCESS";
export const PLOT_TRANSFER_REQ_APPROVAL_FAILURE =
  "PLOT_TRANSFER_REQ_APPROVAL_FAILURE";
export const PLOT_TRANSFER_REQ_APPROVAL_PATH = "requestforApprovalV2";

export const GET_PLOT_TRANSFER_PLOTINFO_BY_ID =
  "GET_PLOT_TRANSFER_PLOTINFO_BY_ID";
export const GET_PLOT_TRANSFER_PLOTINFO_BY_ID_SUCCESS =
  "GET_PLOT_TRANSFER_PLOTINFO_BY_ID_SUCCESS";
export const GET_PLOT_TRANSFER_PLOTINFO_BY_ID_FAILURE =
  "GET_PLOT_TRANSFER_PLOTINFO_BY_ID_FAILURE";
export const GET_PLOT_TRANSFER_PLOTINFO_BY_ID_PATH =
  "FullDetailofPaymentstages";
