export const AGENT = "AGENT";
export const AGENT_SUCCESS = "AGENT_SUCCESS";
export const AGENT_FAILURE = "AGENT_FAILURE";
export const AGENT_PATH = "Updateuser";


export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCESS";
export const FETCH_CONTACTS_FAILURE = "FETCH_CONTACTS_FALURE";
export const FETCH_CONTACTS_PATH = "insertnominee";


export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FALURE";


//FIRST API IN APP REQUEST FORM // MUSTAFA 

export const ALL_LEAD_USER = "ALL_LEAD_USER";
export const ALL_LEAD_USER_SUCCESS = "ALL_LEAD_USER_SUCCESS";
export const ALL_LEAD_USERS_FAILURE = "ALL_LEAD_USERS_FAILURE";
export const ALL_LEAD_USER_PATH = "showallleaduser"

export const INSERTNOMINEE = "INSERTNOMINEE";
export const INSERTNOMINEE_SUCCESS = "INSERTNOMINEE_SUCCESS ";
export const INSERTNOMINEE_FAILURE = "INSERTNOMINEE_FAILURE ";
export const INSERTNOMINEE_PATH = "insertnominee";


export const ALLPOSITION = "ALLPOSITION";
export const ALLPOSITION_SUCCESS = "ALLPOSITION_SUCCESS ";
export const ALLPOSITION_FAILURE = "ALLPOSITION_FAILURE ";
export const ALLPOSITION_PATH = "Position";

export const PLOTPOSITION = "PLOTPOSITION";
export const PLOTPOSITION_SUCCESS = "PLOTPOSITION_SUCCESS ";
export const PLOTPOSITION_FAILURE = "PLOTPOSITION_FAILURE ";
export const PLOTPOSITION_PATH = "PlotPositions";





