export const GET_PAYMENT_BANK = "GET_PAYMENT_BANK";
export const GET_PAYMENT_BANK_SUCCESS = "GET_PAYMENT_BANK_SUCCESS";
export const GET_PAYMENT_BANK_FAILURE = "GET_PAYMENT_BANK_FAILURE";
export const GET_PAYMENT_BANK_PATH = "GetPaymentBank";

export const APPROVE_PAYMENT_BANK = "APPROVE_PAYMENT_BANK";
export const APPROVE_PAYMENT_BANK_SUCCESS = "APPROVE_PAYMENT_BANK_SUCCESS";
export const APPROVE_PAYMENT_BANK_FAILURE = "APPROVE_PAYMENT_BANK_FAILURE";
export const APPROVE_PAYMENT_BANK_PATH = "InsertCompanyWallet";
