export const CALLINGGRAPH= "CALLINGGRAPH";
export const CALLINGGRAPH_SUCCESS = "CALLINGGRAPH_SUCCESS";
export const CALLINGGRAPH_FAILURE = "CALLINGGRAPH_FAILURE";
export const CALLINGGRAPH_PATH = "CallGraphs";