export const FETCH_ALL_SUPPORT = "FETCH_ALL_SUPPORT";
export const FETCH_ALL_SUPPORT_SUCCESS = "FETCH_ALL_SUPPORT_SUCCESS";
export const FETCH_ALL_SUPPORT_FAILURE = "FETCH_ALL_SUPPORT_FAILURE";
export const FETCH_ALL_SUPPORT_PATH = "getAllSupport";

export const FETCH_STATUS = "FETCH_STATUS";
export const FETCH_STATUS_SUCCESS = "FETCH_STATUS_SUCCESS";
export const FETCH_STATUS_FAILURE = "FETCH_STATUS_FAILURE";
export const FETCH_STATUS_PATH = "getSupportStatus";

export const UPDATE_SUPPORT_STATUS = "UPDATE_SUPPORT_STATUS";
export const UPDATE_SUPPORT_STATUS_SUCCESS = "UPDATE_SUPPORT_STATUS_SUCCESS";
export const UPDATE_SUPPORT_STATUS_FAILURE = "UPDATE_SUPPORT_STATUS_FAILURE";
export const UPDATE_SUPPORT_STATUS_PATH = "UpdateSupportStatus";

export const FETCH_FILES = "FETCH_FILES";
export const FETCH_FILES_SUCCESS = "FETCH_FILES_SUCCESS";
export const FETCH_FILES_FAILURE = "FETCH_FILES_FAILURE";
export const FETCH_FILES_PATH = "getSupportImages";