export const PROJECT= "PROJECT";
export const PROJECT_SUCCESS = "PROJECT_SUCCESS";
export const PROJECT_FAILURE = "PROJECT_FAILURE";
export const PROJECT_PATH = "Projects";

export const PLOTCATEGORY= "PLOTCATEGORY";
export const PLOTCATEGORY_SUCCESS = "PLOTCATEGORY_SUCCESS";
export const PLOTCATEGORY_FAILURE = "PLOTCATEGORY_FAILURE";
export const PLOTCATEGORY_PATH = "ShowAllAgent";


export const PLOTSIZE= "PLOTSIZE";
export const PLOTSIZE_SUCCESS = "PLOTSIZE_SUCCESS";
export const PLOTSIZE_FAILURE = "PLOTSIZE_FAILURE";
export const PLOTSIZE_PATH = "ShowAllAgent";


export const PLOTTYPE= "PLOTTYPE";
export const PLOTTYPE_SUCCESS = "PLOTTYPE_SUCCESS";
export const PLOTTYPE_FAILURE = "PLOTTYPE_FAILURE";
export const PLOTTYPE_PATH = "ShowAllAgent";


export const PLOTSECTOR= "PLOTSECTOR";
export const PLOTSECTOR_SUCCESS = "PLOTSECTOR_SUCCESS";
export const PLOTSECTOR_FAILURE = "PLOTSECTOR_FAILURE";
export const PLOTSECTOR_PATH = "Sectors";

export const PLOTDIRECTION= "PLOTDIRECTION";
export const PLOTDIRECTION_SUCCESS = "PLOTDIRECTION_SUCCESS";
export const PLOTDIRECTION_FAILURE = "PLOTDIRECTION_FAILURE";
export const PLOTDIRECTION_PATH = "ShowAllAgent";

export const PLOTSTREET= "PLOTSTREET";
export const PLOTSTREET_SUCCESS = "PLOTSTREET_SUCCESS";
export const PLOTSTREET_FAILURE = "PLOTSTREET_FAILURE";
export const PLOTSTREET_PATH = "Streets";

export const PLOTNO= "PLOTNO";
export const PLOTNO_SUCCESS = "PLOTNO_SUCCESS";
export const PLOTNO_FAILURE = "PLOTNO_FAILURE";
export const PLOTNO_PATH = "Plots";

export const SELLPLOT= "SELLPLOT";
export const SELLPLOT_SUCCESS = "SELLPLOT_SUCCESS";
export const SELLPLOT_FAILURE = "SELLPLOT_FAILURE";
export const SELLPLOT_PATH = "sellplot";



// 1st API hitting in inventory form // Mustafa //

export const PLOT_POSITION= "PLOT_POSITION";
export const PLOT_POSITION_SUCCESS = "PLOT_POSITION_SUCCESS";
export const PLOT_POSITION_FAILURE = "PLOT_POSITION_FAILURE";
export const PLOT_POSITION_PATH = "PlotPositions";